### ISSUE TITLE
How can I get a string result after append?

### ISSUE THREAD

**Issue by jacktan1991** [delmosaurio/stringbuilder#3]
I follow the usage:

```js
var StringBuilder = require('stringbuilder')

var sb = new StringBuilder( {newline:'\r\n'} );
 
sb.append('some text')
sb.append('{0:YYYY}', new Date())
sb.appendLine('some text')
sb.appendLine('{0:$ 0.1}', 50.1044) 
```

now I need the string result holded by `sb`, how?

**Comment by delmosaurio** [comment]
Hi Jack, the lib has not a fulled docs sorry. You can do this:

```
sb.build(function(err, result){
  // the result string 
  console.log(result);
});
```

**Comment by jacktan1991** [comment]
Great & thanks!  I use your codes and it works.

But if I want use it in a non-callback style, something like:

```js

result = sb.build();

// or like Java

result = sb.toString();

```
Does the lib provide those apis?

**Comment by delmosaurio** [comment]
No because the way to build the string is async; at first the libriary was sync but then i convert them like a stream thing, so the only way to do this is async. If you like open a new issue like "synchronously build" to remind me. Thanks.
